estagios/aluno/urls.py
from django.urls import path

from . import views

app_name = 'aluno'

urlpatterns = [
    path('login/', views.login, name='aluno_login'),
    path('logout/', views.logout, name='aluno_logout'),
    path('cadastro_inicial/', views._cadastro_inicial, name='aluno_cadastro_inicial'),
    path('esqueci_senha/', views.esqueceu_senha, name='aluno_esqueceu_senha'),

    path('', views.home, name='aluno_home'),
    path('sobremim/', views.sobre_mim, name='aluno_sobre_mim'),
    path('contato/', views.contato, name='aluno_contato'),
    path('redessociais/', views.redes_sociais, name='aluno_redes_sociais'),

    path('faculdade/', views.faculdade, name='aluno_faculdade'),
    path('faculdade/cadastro/', views.faculdade_cadastro, name='aluno_faculdade_cadastro'),
    path('faculdade/editar/', views.faculdade_editar, name='aluno_faculdade_editar'),
    path('faculdade/excluir/', views.faculdade_excluir, name='aluno_faculdade_excluir'),

    path('outros_cursos/', views.cadastro_extensao, name='aluno_outros_cursos'),
    path('empregos_anteriores/', views.cadastro_empregos_anteriores, name='aluno_outros_empregos'),
    path('diario_aprendizado/', views.diario_aprendizado, name='aluno_diario_aprendizado'),

]

estagios/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from estagios import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('estagios.core.urls')),
    path('alunos/', include('estagios.aluno.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

estagios/aluno/forms.py
from django import forms
from django.forms import ModelForm

from estagios.aluno.models import (
    CHOICES_DEFICIENCIA, CHOICES_SEXO, SobreMimModel, ContatoModel,
    CHOICES_ESTADOS_BRASILEIROS, RedesSociaisModel,
    FaculdadeModel, CHOICES_SITUACAO_ACADEMICA)


class SobreMimForm(ModelForm):
    error_css_class = "error"

    class Meta:
        model = SobreMimModel
        fields = ('data_nascimento', 'sobre_voce')
        fields = fields + ('objetivos_profissionais', 'sexo', 'deficiencia')

        labels = {
            'data_nascimento': 'Data de Nascimento:',
            'sobre_voce': 'Fale sobre você',
            'objetivos_profissionais': 'Fale sobre seus objetivos profissionais',
            'sexo': 'Sexo: ',
            'deficiencia': 'Possui alguma limitação ? ',
        }
        widgets = {
            'data_nascimento': forms.DateInput(
                attrs={
                    'class': 'form-control fa fa-calendar',
                    'placeholder': 'dd/mm/aaaa'
                }
            ),
            'sexo': forms.Select(choices=CHOICES_SEXO,
                                 attrs={
                                     'class': 'form-control'
                                 }),
            'deficiencia': forms.Select(choices=CHOICES_DEFICIENCIA,
                                        attrs={
                                            'class': 'form-control'
                                        }),

            'sobre_voce': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 4,
                'cols': 15,
                'placeholder': 'Fale um pouco sobre você.'
            }),
            'objetivos_profissionais': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 4,
                'cols': 15
            }),
        }
        error_messages = {
            'data_nascimento': {
                'required': ("Digite uma data Válida."),
            },
            'sobre_voce': {
                'required': ("Não deixe este campo em branco. Fale um pouco sobre você."),
            },
            'objetivos_profissionais': {
                'required': ("Não deixe este campo em branco. Fale sobre seus objetivos profissionais."),
            }
        }


class ContatoForm(ModelForm):
    error_css_class = "error"

    class Meta:
        model = ContatoModel
        fields = ('endereco', 'endereco_numero', 'endereco_complemento')
        fields = fields + ('endereco_cidade', 'endereco_estado')
        fields = fields + ('telefone', 'celular', 'telefone_recado')

        labels = {
            'endereco': 'Endereço: ',
            'endereco_numero': 'Número: ',
            'endereco_complemento': 'Complemento:',
            'endereco_cidade': 'Cidade:',
            'endereco_estado': 'Estado:',
            'telefone': 'Telefone:',
            'celular': 'Celular:',
            'telefone_recado': 'Telefone Recado:',
        }
        widgets = {
            'endereco': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Seu endereço',
            }),
            'endereco_numero': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Número',
            }),
            'endereco_complemento': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'apto, bloco, lote',
            }),
            'endereco_cidade': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Cidade',
            }),
            'endereco_estado': forms.Select(choices=CHOICES_ESTADOS_BRASILEIROS,
                                            attrs={
                                                'class': 'form-control'
                                            }),
            'telefone': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Telefone',
            }),
            'celular': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Celular',
            }),
            'telefone_recado': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Telefone para Contato',
            }),
        }
        error_messages = {
            'endereco': {
                'required': ('Digite um endereço.'),
            },
            'endereco_numero': {
                'required': ('Número'),
            },
            'endereco_cidade': {
                'required': ('Digite sua cidade.'),
            },
        }


class RedesSociaisForm(ModelForm):
    error_css_class = "error"

    github = forms.URLField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Preencha com o link do seu GitHub (não obrigatório)',
                'class': 'form-control'
            }
        ),
        required=False,
    )

    facebook = forms.URLField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Preencha com o link do seu Facebook (não obrigatório)',
                'class': 'form-control'
            }
        ),
        required=False,
    )

    linkedin = forms.URLField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Preencha com o link do seu Linkedin (não obrigatório)',
                'class': 'form-control'
            }
        ),
        required=False,
    )

    portfolio = forms.URLField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Preencha com o link do seu portfolio (não obrigatório)',
                'class': 'form-control'
            }
        ),
        required=False,
    )

    class Meta:
        model = RedesSociaisModel
        fields = ()


class FaculdadeForm(ModelForm):
    error_css_class = "error"

    class Meta:
        model = FaculdadeModel
        fields = ('curso', 'instituicao', 'situacao')
        fields = fields + ('carga_horaria', 'data_inicio', 'data_fim')

        labels = {
            'curso': 'Nome do curso',
            'instituicao': 'Instituição: ',
            'situacao': 'Situação ',
            'data_inicio': 'Data de início:',
            'data_fim': 'Data encerramento / previsão:',
            'carga_horaria': 'Carga Horária do curso:',
        }
        widgets = {
            'curso': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Curso',
            }),
            'instituicao': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Faculdade / Universidade',
            }),
            'situacao': forms.Select(choices=CHOICES_SITUACAO_ACADEMICA, attrs={
                'class': 'form-control'
            }),
            'data_inicio': forms.DateInput(attrs={
                'class': 'form-control fa fa-calendar',
                'placeholder': 'dd/mm/aaaa'
            }),
            'data_fim': forms.DateInput(attrs={
                'class': 'form-control fa fa-calendar',
                'placeholder': 'dd/mm/aaaa'
            }),
            'carga_horaria': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Carga horária do curso',
            }),
        }
        error_messages = {
            'data_inicio': {
                'required': ("Digite uma data de início."),
            },
            'curso': {
                'required': ("Digite o nome do curso"),
            },
            'instituicao': {
                'required': ("Digite o nome da faculdade / universidade"),
            }
        }

    def clean_data_fim(self):
        if not self.cleaned_data['data_fim']:
            return False
        return self.cleaned_data['data_fim']

    def clean_situacao(self):
        if not self.cleaned_data['situacao']:
            return False
        return self.cleaned_data['situacao']

    def clean_carga_horaria(self):
        if not self.cleaned_data['carga_horaria']:
            return False
        return self.cleaned_data['carga_horaria']

estagios/aluno/views.py
from django.contrib.auth import logout as auth_logout
from django.shortcuts import redirect, render

from estagios.aluno.forms import SobreMimForm, ContatoForm, RedesSociaisForm, FaculdadeForm
from estagios.aluno.models import SobreMimModel, ContatoModel, RedesSociaisModel, FaculdadeModel
from estagios.core.decorators import area_student
from estagios.core.form import LoginForm, NomeCompletoForm
from estagios.core.functions import auth_request
from estagios.core.functions import registro_novo_aluno
from estagios.core.models import User


def login(request):
    if request.method == "GET":
        return render(request, 'aluno_login.html')
    else:
        if auth_request(request):
            return redirect('aluno:aluno_home')
        else:
            return render(request, 'aluno_login.html')


def logout(request):
    auth_logout(request)
    return render(request, 'aluno_login.html')


def _cadastro_inicial(request):
    if request.method == "GET":
        return render(request, 'aluno_cadastro_inicial.html')
    else:
        return _efetivar_cadastro(request)


def _efetivar_cadastro(request):
    form = LoginForm(request.POST)
    if not form.is_valid():
        return render(request, 'aluno_login.html')
    else:
        email = request.POST['username']
        password = request.POST['password']
        if registro_novo_aluno(email, password):
            auth_request(request)
            return redirect('aluno:aluno_home')
        else:
            return render(request, 'aluno_login.html')


def _sobre_mim_atualizar(request):
    form = SobreMimForm(request.POST)
    form_nome = NomeCompletoForm(request.POST)
    form_nome.is_valid()
    if not form.is_valid() and not form_nome.is_valid():
        context = {'form': form,
                   'formUsername': form_nome}
    else:
        SobreMimModel.objects.update(**form.cleaned_data)
        User.objects.update(**form_nome.cleaned_data)
        dados = SobreMimModel.objects.get(user=request.user).__dict__
        dados_user = User.objects.get(email=request.user).__dict__
        context = {'form': SobreMimForm(dados),
                   'formUsername': NomeCompletoForm(dados_user)}
    return context


def _contato_atualizar(request):
    form = ContatoForm(request.POST)
    if not form.is_valid():
        context = {'form': form}
    else:
        ContatoModel.objects.update(**form.cleaned_data)
        dados = ContatoModel.objects.get(user=request.user).__dict__
        context = {'form': ContatoForm(dados)}
    return context


def _redes_sociais_atualizar(request):
    form = RedesSociaisForm(request.POST)
    if not form.is_valid():
        context = {'form': form}
    else:
        RedesSociaisModel.objects.update(**form.cleaned_data)
        dados = RedesSociaisModel.objects.get(user=request.user).__dict__
        context = {'form': RedesSociaisForm(dados)}
    return context


def _faculdade_index(request):
    url = 'aluno_faculdade.html'
    faculdades = FaculdadeModel.objects.filter(user=request.user)
    context = {'faculdades': faculdades}
    return context, url


def _faculdade_cadastrar(request):
    form = FaculdadeForm(request.POST)
    form.is_valid()
    if not form.is_valid():
        url = 'aluno_faculdade_cadastrar.html'
        context = {'form': form}
    else:
        faculdade = FaculdadeModel(**form.cleaned_data)
        faculdade.user = request.user
        faculdade.save()
        context, url = _faculdade_index(request)
    return context, url


def _faculdade_editar(request):
    try:
        pk = request.POST['pk']
        faculdade = FaculdadeModel.objects.get(pk=pk).__dict__
        form = FaculdadeForm(faculdade)
        url = 'aluno_faculdade_editar.html'
        context = {'form': form, 'pk': pk}
    except:
        pk = request.POST['chave_primaria']
        form = FaculdadeForm(request.POST)
        if not form.is_valid():
            context, url = _faculdade_index(request)
        else:
            faculdade = FaculdadeModel.objects.filter(pk=pk)
            faculdade.update(**form.cleaned_data)
            context, url = _faculdade_index(request)
    return context, url


@area_student
def home(request):
    context = {}
    return render(request, 'aluno_index.html', context)


@area_student
def sobre_mim(request):
    if request.method == "GET":
        dados = SobreMimModel.objects.get(user=request.user).__dict__
        dados_user = User.objects.get(email=request.user).__dict__
        context = {'form': SobreMimForm(dados),
                   'formUsername': NomeCompletoForm(dados_user)}
    else:
        context = _sobre_mim_atualizar(request)
    return render(request, 'aluno_sobre_mim.html', context)


@area_student
def contato(request):
    if request.method == "GET":
        dados = ContatoModel.objects.get(user=request.user).__dict__
        context = {'form': ContatoForm(dados)}
    else:
        context = _contato_atualizar(request)
    return render(request, 'aluno_contato.html', context)


@area_student
def redes_sociais(request):
    if request.method == "GET":
        dados = RedesSociaisModel.objects.get(user=request.user).__dict__
        context = {'form': RedesSociaisForm(dados)}
    else:
        context = _redes_sociais_atualizar(request)
    return render(request, 'aluno_redes_sociais.html', context)


@area_student
def faculdade(request):
    context, url = _faculdade_index(request)
    return render(request, url, context)


@area_student
def faculdade_cadastro(request):
    if request.method == "GET":
        url = 'aluno_faculdade_cadastrar.html'
        context = {'form': FaculdadeForm()}
    else:
        context, url = _faculdade_cadastrar(request)
    return render(request, url, context)


@area_student
def faculdade_editar(request):
    if request.method == "GET":
        context, url = _faculdade_index(request)
    else:
        context, url = _faculdade_editar(request)
    return render(request, url, context)


@area_student
def faculdade_excluir(request):
    if request.method == "GET":
        context, url = _faculdade_index(request)
    else:
        pk = request.POST['chave_primaria']
        FaculdadeModel.objects.get(pk=pk).delete()
        context, url = _faculdade_index(request)
    return render(request, url, context)


@area_student
def cadastro_extensao(request):
    context = {}
    return render(request, 'aluno_outros_cursos.html', context)


@area_student
def cadastro_empregos_anteriores(request):
    context = {}
    return render(request, 'aluno_outros_empregos.html', context)


@area_student
def diario_aprendizado(request):
    context = {}
    return render(request, 'aluno_diario_aprendizado.html', context)


@area_student
def esqueceu_senha(request):
    context = {}
    return render(request, 'aluno_contato.html', context)

estagios/aluno/templates/aluno_base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="pt_br">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Estágio Nota 10</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <!-- Page level plugin CSS-->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    <!-- DataPicker -->
    <link href="{% static 'css/bootstrap-datapicker.css' %}" rel="stylesheet">


</head>

<body id="page-top">

<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="index.html">Estágio Nota 10</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar  -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
        </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-address-card fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'aluno:aluno_diario_aprendizado' %}">Diário do Aprendizado</a>
                <a class="dropdown-item" href="#">Acessos</a>
            </div>
        </li>
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-circle fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">Configurações</a>
                <a class="dropdown-item" href="#">Acessos</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'aluno:aluno_logout' %}" data-toggle="modal"
                   data-target="#logoutModal">Logout</a>
            </div>
        </li>
    </ul>

</nav>

<div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'aluno:aluno_home' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Painel de Controle</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'aluno:aluno_sobre_mim' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>Sobre mim</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'aluno:aluno_contato' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>Contato</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'aluno:aluno_redes_sociais' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>Redes Sociais</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'aluno:aluno_faculdade' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>Faculdade</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'aluno:aluno_outros_cursos' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>Outros cursos</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'aluno:aluno_outros_empregos' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>Empregos Anteriores</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'aluno:aluno_diario_aprendizado' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>Diário do aprendizado</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'aluno:aluno_logout' %}">
                <i class="fas fa-fw fa-atlas"></i>
                <span>Sair</span></a>
        </li>
    </ul>

    <div id="content-wrapper">

        {% block content %}{% endblock %}

        <!-- Sticky Footer -->
        <footer class="sticky-footer">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Estagio Nota 10</span>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.content-wrapper -->
</div>
<!-- /#wrapper -->
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Deseja realmente sair ?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Selecione "Sair" para realmente sair desta sessão.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                <a class="btn btn-primary" href="{% url 'aluno:aluno_logout' %}">Sair</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Page level plugin JavaScript-->
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin.min.js' %}"></script>

<!-- Demo scripts for this page-->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
<script src="{% static 'js/demo/chart-area-demo.js' %}"></script>

<!-- Data Picker includes -->
<script src="{% static 'js/moment.js' %}"></script>
<script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
<script src="{% static 'js/aluno_datapicker.js' %}"></script>

</body>

</html>

estagios/aluno/templates/aluno_cadastro.html
{% extends "aluno_base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Dashboard</a>
            </li>
            <li class="breadcrumb-item active">Cadastro de Dados Pessoais</li>
        </ol>

        <!-- DataTables Example -->
        <div class="card mb-3">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Cadastro de dados Pessoais
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    SEU FORM AQUI
                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>

    </div>
    <!-- /.container-fluid -->


{% endblock %}

estagios/aluno/templates/aluno_cadastro_inicial.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="pt_BR">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Estágio Nota 10</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

</head>

<body class="bg-dark">

<div class="container">
    <div class="card card-login mx-auto mt-5">
        <div class="card-header">Cadastro Inicial</div>
        <div class="card-body">
            <form method="post" action="{% url 'aluno:aluno_cadastro_inicial' %}">
                {% csrf_token %}
                <div class="form-group">
                    <div class="form-label-group">
                        <input type="email" id="inputEmail" name="username" class="form-control"
                               placeholder="Email address" required="required" autofocus="autofocus">
                        <label for="inputEmail">E-mail</label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-label-group">
                        <input type="password" id="inputPassword" name="password" class="form-control"
                               placeholder="Password" required="required">
                        <label for="inputPassword">Senha</label>
                    </div>
                </div>
                <button class="btn btn-primary btn-block" type="submit">Cadastrar-se</button>
            </form>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>


</body>

</html>

estagios/aluno/templates/aluno_diario_aprendizado.html
{% extends "aluno_base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'aluno:aluno_home' %}">Painel de Controle</a>
            </li>
            <li class="breadcrumb-item active">Diário de Aprendizado</li>
        </ol>

        <!-- DataTables Example -->
        <div class="card mb-3">
            <div class="card-header">
                <i class="fas fa-table"></i>
                O que você aprendeu hoje ?
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    SEU FORM AQUI
                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>

    </div>
    <!-- /.container-fluid -->


{% endblock %}

estagios/aluno/templates/aluno_faculdade.html
{% extends "aluno_base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'aluno:aluno_home' %}">Painel de Controle</a>
            </li>
            <li class="breadcrumb-item active">Universidades e Faculdades</li>
        </ol>

        <!-- Div Dados -->
        <div class="card mb-3">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Em que curso você estuda / estudou ?
            </div>
            <div class="card-body">
                <div class="table-responsive">
                </div>
                {% for faculdade in faculdades %}
                <div class="row">
                    <div class="col-sm-2">
                    </div>
                    <div class="col-sm-6">
                        <form action="{% url 'aluno:aluno_faculdade_editar' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="pk" value="{{ faculdade.id }}">
                            <button class="btn btn-primary btn-block" type="submit">
                                {{ faculdade }}
                            </button>
                            <br>
                        </form>
                    </div>
                </div>

                {% endfor %}
                <br>
                <div class="row">
                    <div class="col-sm-4">
                        <form action="{% url 'aluno:aluno_faculdade_cadastro' %}" method="GET">
                            <button class="btn btn-primary btn-block" type="submit">Cadastrar</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card-footer small text-muted">Cadastre os cursos de graduação e pós-graduação</div>
        </div>
    </div>

{% endblock %}

estagios/aluno/templates/aluno_outros_cursos.html
{% extends "aluno_base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'aluno:aluno_home' %}">Painel de Controle</a>
            </li>
            <li class="breadcrumb-item active">Cursos extras e extensão</li>
        </ol>

        <!-- DataTables Example -->
        <div class="card mb-3">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Além do curso superior, quais outros cursos você realizou ?
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    SEU FORM AQUI
                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>

    </div>
    <!-- /.container-fluid -->


{% endblock %}