estagios/aluno/urls.py
from django.urls import path

from . import views

app_name = 'aluno'

urlpatterns = [
    path('login/', views.login, name='aluno_login'),
    path('logout/', views.logout, name='aluno_logout'),
    path('cadastro_inicial/', views._cadastro_inicial, name='aluno_cadastro_inicial'),
    path('esqueci_senha/', views.esqueceu_senha, name='aluno_esqueceu_senha'),

    path('', views.home, name='aluno_home'),
    path('sobremim/', views.sobre_mim, name='aluno_sobre_mim'),
    path('contato/', views.contato, name='aluno_contato'),
    path('redessociais/', views.redes_sociais, name='aluno_redes_sociais'),

    path('faculdade/', views.faculdade, name='aluno_faculdade'),
    path('faculdade/cadastro/', views.faculdade_cadastro, name='aluno_faculdade_cadastro'),
    path('faculdade/editar/', views.faculdade_editar, name='aluno_faculdade_editar'),
    path('faculdade/excluir/', views.faculdade_excluir, name='aluno_faculdade_excluir'),

    path('outros_cursos/', views.cadastro_extensao, name='aluno_outros_cursos'),
    path('empregos_anteriores/', views.cadastro_empregos_anteriores, name='aluno_outros_empregos'),
    path('diario_aprendizado/', views.diario_aprendizado, name='aluno_diario_aprendizado'),

]

estagios/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='core_home'),
]

estagios/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from estagios import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('estagios.core.urls')),
    path('alunos/', include('estagios.aluno.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

estagios/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    is_worker = models.BooleanField(default=False)


class TimeStampedModel(models.Model):
    criado_em = models.DateTimeField(
        verbose_name='criado em',
        auto_now_add=True,
        auto_now=False
    )
    modificado_em = models.DateTimeField(
        verbose_name='modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

estagios/core/views.py
from django.shortcuts import render


def home(request):
    context = {}
    return render(request, 'index.html', context)

estagios/core/templates/index.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Estágio Nota 10</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'fonts/font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <!-- Stylesheet
        ================================================== -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,700,800,600,300" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<div id="preloader">
    <div id="status"><img src="{% static 'img/preloader.gif' %}" height="64" width="64" alt=""></div>
</div>
<!-- Navigation -->
<!-- Photo by Caspar Camille Rubin on Unsplash -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse"><i
                    class="fa fa-bars"></i></button>
            <a class="navbar-brand page-scroll" href="#page-top"> <i class="fa fa-paper-plane-o"></i> Estágio Nota
                10</a></div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden"><a href="#page-top"></a></li>
                <li><a class="page-scroll" href="#about">Sobre nós</a></li>
                <li><a class="page-scroll" href="#alunos">Estudantes</a></li>
                <li><a class="page-scroll" href="#professores">Professores</a></li>
                <li><a class="page-scroll" href="#empresas">Empresas</a></li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Header -->
<div id="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <h1>Estágio <span class="brand-heading">Nota 10</span></h1>
                    <p class="intro-text">Uma plataforma para unir estudantes, professores e empresas</p>
                    <a href="#about" class="btn btn-default page-scroll">Saiba mais</a></div>
            </div>
        </div>
    </div>
</div>
<!-- Sobre Nós -->
<div id="about">
    <div class="container">
        <div class="section-title text-center center">
            <h2>Sobre nós</h2>
            <hr>
        </div>
        <div class="row">
            <div class="col-md-4"><img src="{% static 'img/about.jpg' %}" class="img-responsive"></div>
            <div class="col-md-4">
                <div class="about-text">
                    <h4>Quem Somos nós ?</h4>
                    <p>Desenvolvemos uma plataforma para unir estudantes, professores e empresários.</p>
                    <p><a class="page-scroll" href="#team">Conheça nossa equipe</a>. </p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="about-text">
                    <h4>Como todos ganham ?</h4>
                    <ul>
                        <li>O <b>estudante</b> elabora seu curriculo e interage com a plataforma, registrando seus
                            avanços, como um diário de bordo.
                        </li>
                        <li>O <b>professor </b> pode registrar um depoimento ou recomendação sobre seus alunos, conforme
                            observa em sala de aula algum comportamento ou conhecimento excepcional.
                        </li>
                        <li>A <b>empresa</b> descobre e conhece talentos, tendo mais informações sobre seus estagiários
                            ou candidatos a estágio, fortalecendo um vínculo de confiança entre faculdade e empresa.
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Alunos -->
<div id="alunos" class="text-center">
    <div class="container">
        <div class="section-title center">
            <h2>Estudantes</h2>
            <hr>
        </div>
        <div class="space"></div>
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <a href="{% url 'aluno:aluno_home' %}">
                    <div class="service"><i class="fa fa-desktop"></i>
                        <h3>Cadastre-se</h3>
                        <p>Crie gratuitamente seu cadastro e tenha um curriculo on-line.</p>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="{% url 'aluno:aluno_home' %}">
                    <div class="service"><i class="fa fa-bullhorn"></i>
                        <h3>Participe</h3>
                        <p>Interagir e registrar os avanços de seus estudos.</p>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="{% url 'aluno:aluno_home' %}">
                    <div class="service"><i class="fa fa-rocket"></i>
                        <h3>Comunique</h3>
                        <p>Com uso de nossa plataforma, </p>
                    </div>
                </a>
            </div>
        </div>
        <div class="space"></div>
    </div>
</div>
<!-- Professores -->
<div id="professores" class="text-center">
    <div class="container">
        <div class="section-title center">
            <h2>Professores</h2>
            <hr>
        </div>
        <div class="space"></div>
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <a href="{% url 'aluno:aluno_home' %}">
                    <div class="service"><i class="fa fa-bullhorn"></i>
                        <h3>Cadastre-se</h3>
                        <p>Crie gratuitamente seu cadastro e tenha um curriculo on-line.</p>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="{% url 'aluno:aluno_home' %}">
                    <div class="service"><i class="fa fa-bullhorn"></i>
                        <h3>Participe</h3>
                        <p>Interagir e registrar os avanços de seus estudos.</p>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="{% url 'aluno:aluno_home' %}">
                    <div class="service"><i class="fa fa-rocket"></i>
                        <h3>Comunique</h3>
                        <p>Com uso de nossa plataforma, </p>
                    </div>
                </a>
            </div>
        </div>
        <div class="space"></div>
    </div>
</div>
<!-- Empresas -->
<div id="empresas">
    <div class="container">
        <div class="section-title text-center center">
            <h2>Empresas</h2>
            <hr>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="row testimonials">
                    <div class="col-sm-4">
                        <blockquote><i class="fa fa-quote-left"></i>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitduis sed dapibus leo nec
                                ornare.</p>
                            <div class="clients-name">
                                <p><strong>John Doe</strong><br>
                                    <em>CEO, Company Inc.</em></p>
                            </div>
                        </blockquote>
                    </div>
                    <div class="col-sm-4">
                        <blockquote><i class="fa fa-quote-left"></i>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitduis sed dapibus leo nec
                                ornare.</p>
                            <div class="clients-name">
                                <p><strong>Jane Doe</strong><br>
                                    <em>CEO, Company Inc.</em></p>
                            </div>
                        </blockquote>
                    </div>
                    <div class="col-sm-4">
                        <blockquote><i class="fa fa-quote-left"></i>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitduis sed dapibus leo nec
                                ornare.</p>
                            <div class="clients-name">
                                <p><strong>Chris Smith</strong><br>
                                    <em>CEO, Company Inc.</em></p>
                            </div>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Equipe -->
<div id="team" class="text-center">
    <div class="container">
        <div class="section-title center">
            <h2>Somos a Estágio Nota 10</h2>
            <hr>
        </div>
        <div id="row">
            <div class="col-xs-6 col-md-3 col-sm-6">
                <div class="thumbnail"><img src="{% static 'img/team/01.jpg' %}" alt="..."
                                            class="img-thumbnail team-img">
                    <div class="caption">
                        <h3>Orlando Saraiva Jr</h3>
                        <p>Fundador / CEO</p>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-md-3 col-sm-6">
                <div class="thumbnail"><img src="{% static 'img/team/02.jpg' %}" alt="..."
                                            class="img-thumbnail team-img">
                    <div class="caption">
                        <h3>Mike Doe</h3>
                        <p>Web Designer</p>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-md-3 col-sm-6">
                <div class="thumbnail"><img src="{% static 'img/team/03.jpg' %}" alt="..."
                                            class="img-thumbnail team-img">
                    <div class="caption">
                        <h3>Jane Doe</h3>
                        <p>Creative Director</p>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-md-3 col-sm-6">
                <div class="thumbnail"><img src="{% static 'img/team/04.jpg' %}" alt="..."
                                            class="img-thumbnail team-img">
                    <div class="caption">
                        <h3>Larry Show</h3>
                        <p>Project Manager</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="footer">
    <div class="container">
        <p>Copyright &copy; Modus. Designed by <a href="http://www.templatewire.com" rel="nofollow">TemplateWire</a></p>
    </div>
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script type="text/javascript" src="{% static 'js/jquery.1.11.1.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/SmoothScroll.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.isotope.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.parallax.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jqBootstrapValidation.js' %}"></script>

<!-- Javascripts
    ================================================== -->
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>
</html>